const types = {
  AUTH_FETCH: "AUTH/fetch",
  AUTH_SUCCESS: "AUTH/success",
  AUTH_ERROR: "AUTH/error",

  SCREEN_LOADER_SET: "SCREEN_LOADER/set",

  USER_LOGIN_FETCH: "USER_LOGIN/fetch",
  USER_LOGIN_SUCCESS: "USER_LOGIN/success",
  USER_LOGIN_ERROR: "USER_LOGIN/error",

  USER_LOGOUT_FETCH: "USER_LOGOUT/fetch",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT/success",
  USER_LOGOUT_ERROR: "USER_LOGOUT/error",

  USER_PROFILE_FETCH: "USER_PROFILE/fetch",
  USER_PROFILE_DATA: "USER_PROFILE/data",
  USER_PROFILE_ERROR: "USER_PROFILE/error",
  USER_PROFILE_RESET: "USER_PROFILE/reset",

  USERS_FETCH: "USERS/fetch",
  USERS_DATA: "USERS/data",
  USERS_ERROR: "USERS/error",

  USER_DETAIL_FETCH: "USER_DETAIL/fetch",
  USER_DETAIL_DATA: "USER_DETAIL/data",
  USER_DETAIL_ERROR: "USER_DETAIL/error",

  ADD_USER_FETCH: "ADD_USER/fetch",
  ADD_USER_SUCCESS: "ADD_USER/SUCCESS",
  ADD_USER_ERROR: "ADD_USER/error",

  UPDATE_USER_FETCH: "UPDATE_USER/fetch",
  UPDATE_USER_SUCCESS: "UPDATE_USER/SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER/error",

  ROLES_FETCH: "ROLES/fetch",
  ROLES_DATA: "ROLES/data",
  ROLES_ERROR: "ROLES/error",

  EMPLOYEES_FETCH: "EMPLOYEES/fetch",
  EMPLOYEES_DATA: "EMPLOYEES/data",
  EMPLOYEES_ERROR: "EMPLOYEES/error",

  SERVICE_CENTERS_FETCH: "SERVICE_CENTERS/fetch",
  SERVICE_CENTERS_DATA: "SERVICE_CENTERS/data",
  SERVICE_CENTERS_ERROR: "SERVICE_CENTERS/error",

  UPDATE_SERVICE_CENTER_FETCH: "UPDATE_SERVICE_CENTER/fetch",
  UPDATE_SERVICE_CENTER_SUCCESS: "UPDATE_SERVICE_CENTER/success",
  UPDATE_SERVICE_CENTER_ERROR: "UPDATE_SERVICE_CENTER/error",

  USER_SERVICE_CENTERS_FETCH: "USER_SERVICE_CENTERS/fetch",
  USER_SERVICE_CENTERS_DATA: "USER_SERVICE_CENTERS/data",
  USER_SERVICE_CENTERS_ERROR: "USER_SERVICE_CENTERS/error",

  VEHICLE_MODELS_FETCH: "VEHICLE_MODELS/fetch",
  VEHICLE_MODELS_DATA: "VEHICLE_MODELS/data",
  VEHICLE_MODELS_ERROR: "VEHICLE_MODELS/error",

  UPDATE_VEHICLE_MODEL_FETCH: "UPDATE_VEHICLE_MODEL/fetch",
  UPDATE_VEHICLE_MODEL_SUCCESS: "UPDATE_VEHICLE_MODEL/success",
  UPDATE_VEHICLE_MODEL_ERROR: "UPDATE_VEHICLE_MODEL/error",

  SLOTS_FETCH: "SLOTS/fetch",
  SLOTS_DATA: "SLOTS/data",
  SLOTS_ERROR: "SLOTS/error",

  BOOKING_STATUSES_FETCH: "BOOKING_STATUSES/fetch",
  BOOKING_STATUSES_DATA: "BOOKING_STATUSES/data",
  BOOKING_STATUSES_ERROR: "BOOKING_STATUSES/error",

  AVAILABLE_SLOTS_FETCH: "AVAILABLE_SLOTS/fetch",
  AVAILABLE_SLOTS_DATA: "AVAILABLE_SLOTS/data",
  AVAILABLE_SLOTS_ERROR: "AVAILABLE_SLOTS/error",

  BOOKING_TRANSACTIONS_FETCH: "BOOKING_TRANSACTIONS/fetch",
  BOOKING_TRANSACTIONS_DATA: "BOOKING_TRANSACTIONS/data",
  BOOKING_TRANSACTIONS_ERROR: "BOOKING_TRANSACTIONS/error",

  BOOKING_TRANSACTIONS_BY_MONTH_FETCH: "BOOKING_TRANSACTIONS_BY_MONTH/fetch",
  BOOKING_TRANSACTIONS_BY_MONTH_DATA: "BOOKING_TRANSACTIONS_BY_MONTH/data",
  BOOKING_TRANSACTIONS_BY_MONTH_ERROR: "BOOKING_TRANSACTIONS_BY_MONTH/error",

  BOOKING_TRANSACTIONS_BY_TODAY_SERVICE_CENTER_FETCH:
    "BOOKING_TRANSACTIONS_BY_TODAY_SERVICE_CENTER/fetch",
  BOOKING_TRANSACTIONS_BY_TODAY_SERVICE_CENTER_DATA:
    "BOOKING_TRANSACTIONS_BY_TODAY_SERVICE_CENTER/data",
  BOOKING_TRANSACTIONS_BY_TODAY_SERVICE_CENTER_ERROR:
    "BOOKING_TRANSACTIONS_BY_TODAY_SERVICE_CENTER/error",

  SERVICE_CENTER_STAFF_FETCH: "SERVICE_CENTER_STAFF/fetch",
  SERVICE_CENTER_STAFF_DATA: "SERVICE_CENTER_STAFF/data",
  SERVICE_CENTER_STAFF_ERROR: "SERVICE_CENTER_STAFF/error",

  BOOKING_TRANSACTION_CREATE_FETCH: "BOOKING_TRANSACTION_CREATE/fetch",
  BOOKING_TRANSACTION_CREATE_SUCCESS: "BOOKING_TRANSACTION_CREATE/success",
  BOOKING_TRANSACTION_CREATE_ERROR: "BOOKING_TRANSACTION_CREATE/error",

  BOOKING_TRANSACTION_UPDATE_FETCH: "BOOKING_TRANSACTION_UPDATE/fetch",
  BOOKING_TRANSACTION_UPDATE_SUCCESS: "BOOKING_TRANSACTION_UPDATE/success",
  BOOKING_TRANSACTION_UPDATE_ERROR: "BOOKING_TRANSACTION_UPDATE/error",

  SEARCH_CUSTOMERS_BY_MOBILE_FETCH: "SEARCH_CUSTOMERS_BY_MOBILE/fetch",
  SEARCH_CUSTOMERS_BY_MOBILE_DATA: "SEARCH_CUSTOMERS_BY_MOBILE/data",
  SEARCH_CUSTOMERS_BY_MOBILE_ERROR: "SEARCH_CUSTOMERS_BY_MOBILE/error",
  SEARCH_CUSTOMERS_BY_MOBILE_RESET: "SEARCH_CUSTOMERS_BY_MOBILE/reset",

  STAFF_HOLIDAYS_BY_MONTH_SERVICE_CENTER_FETCH:
    "STAFF_HOLIDAYS_BY_MONTH_SERVICE_CENTER/fetch",
  STAFF_HOLIDAYS_BY_MONTH_SERVICE_CENTER_DATA:
    "STAFF_HOLIDAYS_BY_MONTH_SERVICE_CENTER/data",
  STAFF_HOLIDAYS_BY_MONTH_SERVICE_CENTER_ERROR:
    "STAFF_HOLIDAYS_BY_MONTH_SERVICE_CENTER/error",

  STAFF_HOLIDAYS_CREATE_DELETE_FETCH: "STAFF_HOLIDAYS_CREATE_DELETE/fetch",
  STAFF_HOLIDAYS_CREATE_DELETE_SUCCESS: "STAFF_HOLIDAYS_CREATE_DELETE/success",
  STAFF_HOLIDAYS_CREATE_DELETE_ERROR: "STAFF_HOLIDAYS_CREATE_DELETE/error",

  VEHICLE_OPERATIONS_FETCH: "VEHICLE_OPERATIONS/fetch",
  VEHICLE_OPERATIONS_DATA: "VEHICLE_OPERATIONS/data",
  VEHICLE_OPERATIONS_ERROR: "VEHICLE_OPERATIONS/error",
};
export default types;
